export const pdfs = [{
    id: 1,
    pdf: '/Eastern_Front_Data/Breakout_at_Klin.pdf',
    image: '/Eastern_Front_Data/breakout_at_klin.PNG',
    filter: 'Eastern Front',
    name: 'Breakout at Klin'
},
{
    id: 2,
    pdf: 'Eastern_Front_Data/Breakout_to_Lisyanka.pdf',
    image: './Eastern_Front_Data/breakout_to_lisyanka.PNG',
    filter: 'Eastern Front',
    name: 'Breakout at Lisyanka',
},
{
    id: 3,
    pdf: './Eastern_Front_Data/Bug_River.pdf',
    image: '/Eastern_Front_Data/bug_river.PNG',
    filter: 'Eastern Front',
    name: 'Bug River',
},
{
    id: 4,
    pdf: './Eastern_Front_Data/gates_of_moscow.pdf',
    image: './Eastern_Front_Data/gates_of_moscow.PNG',
    filter: 'Eastern Front',
    name: 'Gates of Moscow',
},
{
    id: 5,
    pdf: './Eastern_Front_Data/Ponyri.pdf',
    image: './Eastern_Front_Data/ponyri.PNG',
    filter: 'Eastern Front',
    name: 'Ponyri',
},
{
    id: 6,
    pdf: './Eastern_Front_Data/Red_Barricades_Factory.pdf',
    image: './Eastern_Front_Data/red_barricades_factory.PNG',
    filter: 'Eastern Front',
    name: 'Red Barricades Factory',
},
{
    id: 7,
    pdf: './Eastern_Front_Data/Suomussalmi.pdf',
    image: './Eastern_Front_Data/suomussalmi.PNG',
    filter: 'Eastern Front',
    name: 'Suomussalmi',
},
{
    id: 8,
    pdf: require('./MedTheaterData/1st_Armoured_to_the_rescue.pdf'),
    image: './MedTheaterData/first_armored_rescue.PNG',
    filter: 'Mediterranean Theater',
    name: 'First Armoured to the rescue',
},
{
    id: 9,
    pdf: require('./MedTheaterData/Dug_in_at_Sidi_Omar.pdf'),
    image: require('./MedTheaterData/dug_in_sidi_omar.PNG'),
    filter: 'Mediterranean Theater',
    name: 'Dug in at Sidi Omar',
},
{
    id: 10,
    pdf: require('./MedTheaterData/Escape_via_the_Coastal_Road.pdf'),
    image: require('./MedTheaterData/escape_via_the_coast.PNG'),
    filter: 'Mediterranean Theater',
    name: 'Escape via the Coastal Road',
},
{
    id: 11,
    pdf: require('./MedTheaterData/Flanking_Maneuver_at_Bir_Hakeim.pdf'),
    image: require('./MedTheaterData/flanking_manuever_bir_hakeim.PNG'),
    filter: 'Mediterranean Theater',
    name: 'Flanking Maneuver at Bir Hakeim',
},
{
    id: 12,
    pdf: require('./MedTheaterData/Hellfire_Pass.pdf'),
    image: require('./MedTheaterData/hellfire_pass.PNG'),
    filter: 'Mediterranean Theater',
    name: 'Hellfire Pass',
},
{
    id: 13,
    pdf: require('./MedTheaterData/Into_the_Cauldron.pdf'),
    image: require('./MedTheaterData/into_the_cauldron.PNG'),
    filter: 'Mediterranean Theater',
    name: 'Into the Cauldron',
},
{
    id: 14,
    pdf: require('./MedTheaterData/Panzers_versus_Grants.pdf'),
    image: require('./MedTheaterData/panzers_vs_grants.PNG'),
    filter: 'Mediterranean Theater',
    name: 'Panzers versus Grants',
},
{
    id: 15,
    pdf: require('./MedTheaterData/Sidi_Rezegh_Airfield.pdf'),
    image: require('./MedTheaterData/sidi_rezegh_airfield.PNG'),
    filter: 'Mediterranean Theater',
    name: 'Sidi Rezegh Airfield',
},
{
    id: 16,
    pdf: require('./PacificTheaterData/Guam_Landings.pdf'),
    image: require('./PacificTheaterData/guam_landings.PNG'),
    filter: 'Pacific Theater',
    name: 'Guam Landings',
},
{
    id: 17,
    pdf: require('./PacificTheaterData/Japanese_Counter-attack.pdf'),
    image: require('./PacificTheaterData/japanese_counterattack.PNG'),
    filter: 'Pacific Theater',
    name: 'Japanese Counterattack',
},
{
    id: 18,
    pdf: require('./PacificTheaterData/Matanikau_River.pdf'),
    image: require('./PacificTheaterData/matanikau_river.PNG'),
    filter: 'Pacific Theater',
    name: 'Matanikau River',
},
{
    id: 19,
    pdf: require('./PacificTheaterData/Peleliu_Landings_Overlord.pdf'),
    image: require('./PacificTheaterData/peleliu_landings_overlord.PNG'),
    filter: 'Pacific Theater',
    name: 'Peleliu Landings Overlord',
},
{
    id: 20,
    pdf: require('./PacificTheaterData/Slopes_of_Mount_Austen.pdf'),
    image: require('./PacificTheaterData/slopes_of_mount_austen.PNG'),
    filter: 'Pacific Theater',
    name: 'Slopes of Mount Austen',
},
{
    id: 21,
    pdf: require('./PacificTheaterData/Sugar_Loaf_and_Half_Moon.pdf'),
    image: require('./PacificTheaterData/sugar_loaf_half_moon.PNG'),
    filter: 'Pacific Theater',
    name: 'Sugar Loaf and Half Moon',
},
{
    id: 22,
    pdf: require('./PacificTheaterData/The_Meat_Grinder.pdf'),
    image: require('./PacificTheaterData/the_meat_grinder.PNG'),
    filter: 'Pacific Theater',
    name: 'The Meat Grinder',
},
{
    id: 23,
    pdf: require('./PacificTheaterData/Wake_Island.pdf'),
    image: require('./PacificTheaterData/wake_island.PNG'),
    filter: 'Pacific Theater',
    name: 'Wake Island',
},
{
    id: 24,
    pdf: require('./TerrainPackData/Across_the_River_Roer.pdf'),
    image: require('./TerrainPackData/across_the_river_roer.PNG'),
    filter: 'Terrain Pack',
    name: 'Across the River Roer',
},
{
    id: 25,
    pdf: require('./TerrainPackData/Knightsbridge.pdf'),
    image: require('./TerrainPackData/knightsbridge.PNG'),
    filter: 'Terrain Pack',
    name: 'Knightsbridge',
},
{
    id: 26,
    pdf: require('./TerrainPackData/Nijmegen_Bridges.pdf'),
    image: require('./TerrainPackData/nijmegan_bridges.PNG'),
    filter: 'Terrain Pack',
    name: 'Nijmegan Bridges',
},
{
    id: 27,
    pdf: require('./TerrainPackData/Schwammenauel_Dam.pdf'),
    image: require('./TerrainPackData/schwammanuel_dam.PNG'),
    filter: 'Terrain Pack',
    name: 'Schwammenauel Dam',
},
{
    id: 28,
    pdf: require('./base_game_data/Arnhem_Bridge.pdf'),
    image: require('./base_game_data/arnhem_bridge.PNG'),
    filter: 'Base Game',
    name: 'Arnhem Bridge',
},
{
    id: 29,
    pdf: require('./base_game_data/Arracourt.pdf'),
    image: require('./base_game_data/arracourt.PNG'),
    filter: 'Base Game',
    name: 'Arracourt',
},
{
    id: 30,
    pdf: require('./base_game_data/Liberation_of_Paris.pdf'),
    image: require('./base_game_data/liberation_of_paris.PNG'),
    filter: 'Base Game',
    name: 'Liberation of Paris',
},
{
    id: 31,
    pdf: require('./base_game_data/Mont_Mouchet.pdf'),
    image: require('./base_game_data/mont_mouchet.PNG'),
    filter: 'Base Game',
    name: 'Mont Mouchet',
},
{
    id: 32,
    pdf: require('./base_game_data/Montelimar.pdf'),
    image: require('./base_game_data/montelimar.PNG'),
    filter: 'Base Game',
    name: 'Montelimar',
},
{
    id: 33,
    pdf: require('./base_game_data/Omaha_Beach.pdf'),
    image: require('./base_game_data/omaha_beach.PNG'),
    filter: 'Base Game',
    name: 'Omaha Beach',
},
{
    id: 34,
    pdf: require('./base_game_data/Omaha_Beach_Overlord.pdf'),
    image: require('./base_game_data/omaha_overlord.PNG'),
    filter: 'Base Game',
    name: 'Omaha Beach Overlord',
},
{
    id: 35,
    pdf: require('./base_game_data/Operation_Cobra.pdf'),
    image: require('./base_game_data/operation_cobra.PNG'),
    filter: 'Base Game',
    name: 'Operation Cobra',
},
{
    id: 36,
    pdf: require('./base_game_data/Operation_Luttich.pdf'),
    image: require('./base_game_data/operation_luttich.PNG'),
    filter: 'Base Game',
    name: 'Operation Luttich',
},
{
    id: 37,
    pdf: require('./base_game_data/Pegasus_Bridge.pdf'),
    image: require('./base_game_data/pegasus_bridge.PNG'),
    filter: 'Base Game',
    name: 'Pegasus Bridge',
},
{
    id: 38,
    pdf: require('./base_game_data/Pointe-du-Hoc.pdf'),
    image: require('./base_game_data/pointe_du_hoc.PNG'),
    filter: 'Base Game',
    name: 'Point du Hoc',
},
{
    id: 39,
    pdf: require('./base_game_data/Sainte-Mere-Eglise.pdf'),
    image: require('./base_game_data/saint_mere.PNG'),
    filter: 'Base Game',
    name: 'Saint-Mere-Egleise',
},
{
    id: 40,
    pdf: require('./base_game_data/Saverne_Gap.pdf'),
    image: require('./base_game_data/saverne_gap.PNG'),
    filter: 'Base Game',
    name: 'Saverne Gap',
},
{
    id: 41,
    pdf: require('./base_game_data/St_Vith.pdf'),
    image: require('./base_game_data/st_vith.PNG'),
    filter: 'Base Game',
    name: 'St Vith',
},
{
    id: 42,
    pdf: require('./base_game_data/Sword_Beach.pdf'),
    image: require('./base_game_data/sword_beach.PNG'),
    filter: 'Base Game',
    name: 'Sword Beach',
},
{
    id: 43,
    pdf: require('./base_game_data/Toulon.pdf'),
    image: require('./base_game_data/toulon.PNG'),
    filter: 'Base Game',
    name: 'Toulon',
},
{
    id: 44,
    pdf: require('./base_game_data/Vassieux.pdf'),
    image: require('./base_game_data/vassieux.PNG'),
    filter: 'Base Game',
    name: 'Vassieux',
}



]